apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: gitlab
spec:
  replicas: 2
  selector:
    matchLabels:
      run: diplom-app
  template:
    metadata:
      labels:
        run: diplom-app
    spec:
      containers:
      - name: diplom-app
        image: vodyakovdenis/diplom-test-site:__VERSION__
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diplom-app
  namespace: gitlab
spec:
  selector:
    run: diplom-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplom-app
  namespace: gitlab
  labels:
    name: diplom-app
spec:
  ingressClassName: nginx
  rules:
  - host: denis.diplom.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: diplom-app
            port:
              number: 80
